changelog:
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - docs
    - title: Testing and CI
      labels:
        - test
        - ci
    - title: Release and Packaging
      labels:
        - chore
        - release
